version: '3.8'

services:

  psql:
    container_name: finances-psql
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
