version: '3.8'

services:

  psql:
    container_name: finances-psql
    image: postgres:${POSTGRES_VERSION}
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql

  app:
    container_name: finances-next-js
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        NODE_ENV: ${NODE_ENV}
        NODE_PORT: ${NODE_PORT}
    env_file:
      - .env
    ports:
      - 3000:${NODE_PORT}

volumes:
  postgres:
